### ISSUE TITLE
Create README.md injection images

### ISSUE THREAD

**Issue by omurovec** [privacy-scaling-explorations/pse-gfis#7]
# Overview
Github READMEs allow you to inject images into the markdown and this can be helpful to make the good first issue page more accessible

## TODO
- [x] Create api endpoint that returns an SVG for the Repo and good-first-issue issues
- [x] Dynamically hydrate the SVGs with response data from the api
- [x] Support dark & light mode
- [x] Create api endpoint with redirection to the issues on click
